### ISSUE TITLE
Doesn't Work on 5.1+

### ISSUE THREAD

**Issue by Mythical-Github** [dracula/unreal-engine#4]
Manually installing to the slate folder, it does not appear within theme section of the editor preferences tab
importing with the ui button within the editor preferences also gives a failed to import error
though checking the output log shows no errors on this
I also tried this on unreal engine for fortnite and it was unable to be installed, though I don't really imagine they'd work the same anyways

**Comment by hudsonm62** [comment]
It's still working on 5.1 and 5.2, are you sure you installed it correctly?

**Comment by jaaiden** [comment]
As ziro said, I would try giving it another go and see if it works out (force-delete the existing `Themes` folder and remake it - make sure to backup other themes first!). As for the import button, it didn't exist when I originally made the theme so there might be some missing data in the json struct the editor needs to actually perform the import.

I remember checking the source code for the theming engine a while back and didn't see any editor logging in there so I don't think it would report anything to you if a theme fails anyway. Also this theming process hasn't been tested at all with the Fortnite editor so I'm not fully sure if it would work there, I would need to download it and investigate when I (eventually) get the time to do so.

**Comment by Mythical-Github** [comment]
So it seems that there is a slight bug with the engine itself, or maybe there is something wrong on my end
but force creating a generic new one, then applying the dracula one seemed to do the trick
but before creating a new one it absolutely refused to work at all

**Comment by hudsonm62** [comment]
Awesome

Out of my own curiosity/future reference, does the theme work with UEFN?

**Comment by Mythical-Github** [comment]
I stopped looking into uefn, because they pushed verse so hard they removed bp entirely, didn't really have the time to enjoy it
